{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kubed.serviceAccountName" . }}
  labels:
{{ include "kubed.labels" . | indent 4 }}
{{- end -}}
